# Generated by Django 5.1.1 on 2024-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qquantity',
        ),
        migrations.AlterField(
            model_name='question',
            name='qno',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='qquantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sno',
            field=models.PositiveIntegerField(),
        ),
    ]
