# Generated by Django 5.1.1 on 2025-04-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_publication_author_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default='Untitled Paper', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
