# Generated by Django 5.1.1 on 2025-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paper_title_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='combined_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='extra_author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
