# Generated by Django 5.1.1 on 2024-10-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exam_slug_question_slug_subject_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explanation',
            old_name='qno',
            new_name='question',
        ),
        migrations.AddField(
            model_name='explanation',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject'),
        ),
    ]
