# Generated by Django 5.1.1 on 2025-04-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publication_combined_author_publication_extra_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
