# Generated by Django 5.1.1 on 2024-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_examnumber_rename_qtext_question_questiontext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnumber',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='questionquantity',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectnumber',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
