# Generated by Django 5.1.1 on 2024-10-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_question_questionnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='examnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examnumber'),
        ),
    ]
