# Generated by Django 5.1.1 on 2025-08-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wikipage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='author',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
