# Generated by Django 5.1.1 on 2024-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_explanation_examnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examnumber',
            name='examnumber',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='questionquantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectnumber',
            field=models.PositiveIntegerField(),
        ),
    ]
