# Generated by Django 5.1.1 on 2024-10-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_examnumber_examnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='explanation',
            field=models.CharField(max_length=5000),
        ),
    ]
