# Generated by Django 5.1.1 on 2025-08-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_wikipage_author_wikipage_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_versions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.wikipage')),
            ],
        ),
    ]
