# Generated by Django 5.1.1 on 2024-10-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_explanation_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnumber',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam'),
        ),
    ]
