# Generated by Django 5.1.1 on 2025-08-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wikiversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikiversion',
            options={'ordering': ['-edited_at']},
        ),
        migrations.AddIndex(
            model_name='wikiversion',
            index=models.Index(fields=['page', '-edited_at'], name='app_wikiver_page_id_eeacd4_idx'),
        ),
    ]
