# Generated by Django 5.1.1 on 2024-10-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_examnumber_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam'),
        ),
        migrations.AddField(
            model_name='subject',
            name='examnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examnumber'),
        ),
    ]
