# Generated by Django 5.1.1 on 2025-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_wikiversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examtype',
            field=models.CharField(choices=[('License', '자격증'), ('Public', '공무원'), ('Recruit', '기업채용'), ('Other', '기타')], default='License', max_length=20),
        ),
    ]
