# Generated by Django 5.1.1 on 2025-08-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_exam_examtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionnumber1',
            new_name='qnumber',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionnumber2',
            new_name='qsubject',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questiontext',
            new_name='qtext',
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('Sj', '주관식'), ('Oj', '객관식')], default='Sj', max_length=2),
        ),
        migrations.AlterField(
            model_name='examnumber',
            name='examnumber',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'order'], name='app_option_questio_368a16_idx'), models.Index(fields=['question', 'is_correct'], name='app_option_questio_43422c_idx')],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
