# Generated by Django 5.1.1 on 2025-08-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_questionnumber1_question_qnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ragent',
            field=models.CharField(blank=True, choices=[('NAT', '국가직'), ('LOC', '지방직'), ('SEO', '서울시'), ('ASS', '국회직'), ('CRT', '법원직'), ('POL', '검찰/경찰'), ('FIR', '소방'), ('COA', '해경'), ('MIL', '군무원'), ('MET', '기상직'), ('REG', '지역인재'), ('POS', '계리직'), ('NUR', '간호직'), ('CIV', '비상대비')], help_text='examtype=공무원일 때 필수', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Jobseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragent', models.CharField(choices=[('NAT', '국가직'), ('LOC', '지방직'), ('SEO', '서울시'), ('ASS', '국회직'), ('CRT', '법원직')], max_length=3)),
                ('jobseries', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ragent', 'jobseries'], name='app_jobseri_ragent_4b8f8f_idx')],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='jobseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobseries'),
        ),
        migrations.CreateModel(
            name='Rposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragent', models.CharField(choices=[('NAT', '국가직'), ('LOC', '지방직'), ('SEO', '서울시'), ('ASS', '국회직'), ('CRT', '법원직'), ('POL', '검찰/경찰'), ('FIR', '소방'), ('COA', '해경'), ('MIL', '군무원'), ('MET', '기상직'), ('REG', '지역인재'), ('POS', '계리직'), ('NUR', '간호직'), ('CIV', '비상대비')], max_length=3)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['ragent', 'name'], name='app_rpositi_ragent_830713_idx')],
                'unique_together': {('ragent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rposition'),
        ),
    ]
