# Generated by Django 5.1.1 on 2024-10-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_exam_question_examnumber_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
