# Generated by Django 5.1.1 on 2025-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_exam_ragent_jobseries_exam_jobseries_rposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='jobseries',
        ),
        migrations.AlterUniqueTogether(
            name='rposition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exam',
            name='position',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='ragent',
        ),
        migrations.AddField(
            model_name='exam',
            name='r_agent',
            field=models.CharField(blank=True, choices=[('GOV', '국가직'), ('LOCAL', '지방직'), ('SEOUL', '서울시'), ('ASSEMBLY', '국회직'), ('COURT', '법원직'), ('POLICE', '경찰'), ('FIRE', '소방'), ('COAST', '해경'), ('MIL', '군무원'), ('MET', '기상직'), ('TALENT', '지역인재'), ('POST', '계리직'), ('NURSE', '간호직'), ('CIVILDEF', '비상대비')], max_length=20, null=True, verbose_name='채용기관'),
        ),
        migrations.AddField(
            model_name='exam',
            name='r_group',
            field=models.CharField(blank=True, help_text='국가직/지방직/서울시/국회직/법원직은 필수', max_length=20, null=True, unique=True, verbose_name='직류'),
        ),
        migrations.AddField(
            model_name='exam',
            name='r_position',
            field=models.CharField(blank=True, help_text='채용기관별 허용된 직급만 선택/입력 가능합니다.', max_length=20, null=True, verbose_name='직급'),
        ),
        migrations.DeleteModel(
            name='Jobseries',
        ),
        migrations.DeleteModel(
            name='Rposition',
        ),
    ]
