# Generated by Django 5.1.1 on 2025-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_exam_jobseries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='r_agent',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='r_group',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='r_position',
        ),
        migrations.AddField(
            model_name='exam',
            name='ragent',
            field=models.CharField(blank=True, choices=[('국가직', '국가직'), ('지방직', '지방직'), ('서울시', '서울시'), ('국회직', '국회직'), ('법원직', '법원직'), ('경찰', '경찰'), ('소방', '소방'), ('해경', '해경'), ('군무원', '군무원'), ('기상직', '기상직'), ('지역인재', '지역인재'), ('계리직', '계리직'), ('간호직', '간호직'), ('비상대비', '비상대비')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='rgroup',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='rposition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
