# Generated by Django 5.1.1 on 2024-10-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='view',
        ),
    ]
