# Generated by Django 5.1.1 on 2025-08-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_exam_r_agent_remove_exam_r_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qsubject',
        ),
        migrations.AddField(
            model_name='question',
            name='qscript',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ExamQsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examstage', models.CharField(blank=True, choices=[('1st', '1차'), ('2nd', '2차'), ('3rd', '3차')], max_length=3, null=True)),
                ('esn', models.PositiveIntegerField()),
                ('est', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam')),
            ],
            options={
                'ordering': ['exam_id', 'esn'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='examqsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examqsubject'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'examnumber', 'examqsubject', 'qnumber'), name='uniq_question_scope'),
        ),
        migrations.AddConstraint(
            model_name='examqsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'esn'), name='uniq_exam_esn'),
        ),
        migrations.AddConstraint(
            model_name='examqsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'est'), name='uniq_exam_est'),
        ),
    ]
