# Generated by Django 5.1.1 on 2025-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_question_qsubject_question_qscript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examnumber',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='examqsubject',
            name='est',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='examqsubject',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='qscript',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
