# Generated by Django 5.1.1 on 2024-10-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_comment_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app.explanation'),
        ),
    ]
