# Generated by Django 5.1.1 on 2025-08-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_examnumber_slug_alter_examqsubject_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='examqsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examqsubject'),
        ),
    ]
