# Generated by Django 5.1.1 on 2024-10-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comment_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examnumber',
            name='subjectquantity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionnumber',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='examnumber',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='questionquantity',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnumber1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnumber2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='contentnumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='contenttitle',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
