# Generated by Django 5.1.1 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_explanation_examqsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='examqsubject',
        ),
        migrations.AddField(
            model_name='explanation',
            name='examqsubject',
            field=models.ManyToManyField(to='app.examqsubject'),
        ),
    ]
