# Generated by Django 5.1.1 on 2024-10-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_examnumber_subjectquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='slug',
        ),
    ]
