# Generated by Django 5.1.1 on 2025-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_explanation_examqsubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='examqsubject',
        ),
        migrations.AddField(
            model_name='question',
            name='slug1',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
