# Generated by Django 5.1.1 on 2024-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_exam_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='contentnumber',
            new_name='detailnumber',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='slug',
            new_name='detailslug',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='contenttitle',
            new_name='detailtitle',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjectname',
            new_name='mainname',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjectnumber',
            new_name='mainnumber',
        ),
        migrations.AddField(
            model_name='subject',
            name='mainslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
