# Generated by Django 5.2.14 on 2026-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_explanation_examqsubject_question_slug1'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(db_index=True, max_length=64)),
                ('quarter_anchor', models.CharField(help_text="'current' / 'prev_q' / 'prev_y'", max_length=16)),
                ('quarter_date', models.DateField(help_text='기준 분기 첫달 1일')),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='fred', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-quarter_date', 'indicator_key'],
                'indexes': [models.Index(fields=['quarter_date', 'quarter_anchor'], name='app_indicat_quarter_ae9528_idx'), models.Index(fields=['indicator_key'], name='app_indicat_indicat_57fc96_idx')],
                'unique_together': {('indicator_key', 'quarter_anchor', 'quarter_date')},
            },
        ),
    ]
