# Generated by Django 5.1.1 on 2024-10-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_contentnumber_subject_detailnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='mainslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
