# Generated by Django 5.1.1 on 2024-10-12 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_subject_mainslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailnumber', models.PositiveIntegerField(null=True)),
                ('detailtitle', models.CharField(max_length=400, null=True)),
                ('detailslug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examnumber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='explanation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AddField(
            model_name='comment',
            name='detailsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.detailsubject'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='detailsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.detailsubject'),
        ),
        migrations.CreateModel(
            name='Mainsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainnumber', models.PositiveIntegerField()),
                ('mainname', models.CharField(max_length=200)),
                ('mainslug', models.SlugField(blank=True, null=True, unique=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam')),
            ],
        ),
        migrations.AddField(
            model_name='detailsubject',
            name='mainslug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mainsubject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mainsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mainsubject'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='mainsubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mainsubject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
