# Generated by Django 5.2.14 on 2026-05-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_indicatorsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examqsubject',
            options={'ordering': ['exam_id', 'examnumber_id', 'esn']},
        ),
        migrations.RemoveConstraint(
            model_name='examqsubject',
            name='uniq_exam_esn',
        ),
        migrations.RemoveConstraint(
            model_name='examqsubject',
            name='uniq_exam_est',
        ),
        migrations.AddField(
            model_name='examqsubject',
            name='examnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examnumber'),
        ),
        migrations.AddConstraint(
            model_name='examqsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'examnumber', 'esn'), name='uniq_exam_examnumber_esn'),
        ),
        migrations.AddConstraint(
            model_name='examqsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('est', ''), _negated=True), fields=('exam', 'est'), name='uniq_exam_est_non_empty'),
        ),
    ]
