# Generated by Django 5.1.1 on 2024-10-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_detailsubject_remove_explanation_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsubject',
            name='detailnumber',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detailsubject',
            name='detailtitle',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='mainname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='mainnumber',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
