# Generated by Django 5.1.1 on 2026-06-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userformula'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockdailydata',
            new_name='app_stockda_ticker_99d128_idx',
            old_name='app_stockda_ticker_date_idx',
        ),
        migrations.RenameIndex(
            model_name='userformula',
            new_name='app_userfor_user_id_23da7a_idx',
            old_name='app_userfor_user_id_upd_idx',
        ),
        migrations.RemoveField(
            model_name='detailsubject',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mainsubject',
            name='exam',
        ),
        migrations.AlterUniqueTogether(
            name='examnumber',
            unique_together={('exam', 'year', 'examnumber')},
        ),
    ]
