# Generated by Django 5.1.1 on 2024-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_explanation_detailsubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsubject',
            name='detailnumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
