# Generated by Django 5.1.1 on 2024-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_detailsubject_detailnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='mainnumber',
            field=models.PositiveIntegerField(),
        ),
    ]
