# Generated by Django 5.1.1 on 2024-10-15 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='comment_dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanation',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanation',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExplanationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.explanation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['explanation', 'user', 'viewed_at'], name='app_explana_explana_4a1853_idx'), models.Index(fields=['explanation', 'ip_address', 'viewed_at'], name='app_explana_explana_212d39_idx')],
            },
        ),
    ]
