# Generated by Django 5.1.1 on 2024-10-19 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_comment_dislike_comment_like_explanation_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='explanation',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_explanation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_explanation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExplanationView',
        ),
    ]
