# Generated by Django 5.1.1 on 2025-01-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='detailsubject',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='mainsubject',
        ),
        migrations.AddField(
            model_name='explanation',
            name='detailsubject',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='explanation',
            name='mainsubject',
            field=models.JSONField(default=list),
        ),
    ]
