# Generated by Django 5.1.1 on 2025-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_examnumber_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examnumber',
            name='examnumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='examnumber',
            unique_together={('exam', 'examnumber')},
        ),
    ]
