# Generated by Django 5.1.1 on 2025-01-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_examnumber_examnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.CharField(max_length=1000),
        ),
    ]
