# Generated by Django 5.1.1 on 2025-01-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('author', 'Author'), ('translator', 'Translator')], max_length=10)),
                ('producer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='explanation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='explanation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('article', '학술논문'), ('book', '단행본'), ('translation', '번역서'), ('dissertation', '박사학위논문'), ('thesis', '석사학위논문')], max_length=15)),
                ('year', models.PositiveIntegerField()),
                ('title', models.TextField(max_length=1000)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('issue', models.PositiveIntegerField(blank=True, null=True)),
                ('start_page', models.PositiveIntegerField(blank=True, null=True)),
                ('end_page', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.TextField(blank=True, max_length=2000, null=True)),
                ('agency_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.agency')),
                ('author', models.ManyToManyField(limit_choices_to={'job': 'author'}, related_name='authored_publications', to='app.producer')),
                ('translator', models.ManyToManyField(blank=True, limit_choices_to={'job': 'translator'}, related_name='translated_publications', to='app.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('bookmarks', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='app.publication')),
            ],
        ),
    ]
