# Generated by Django 5.1.1 on 2025-01-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_agency_producer_rename_date_explanation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='detailsubject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='examnumber',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='mainsubject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.AddField(
            model_name='comment',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_es', to='app.essay'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_ex', to='app.explanation'),
        ),
    ]
