# Generated by Django 5.1.1 on 2025-03-11 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_comment_detailsubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='content',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='likes',
        ),
        migrations.AddField(
            model_name='essay',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_essay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essay',
            name='essay',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_essay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.publication'),
        ),
    ]
