# Generated by Django 5.1.1 on 2025-03-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_essay_bookmarks_remove_essay_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'job': 'author'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays_author', to='app.producer'),
        ),
        migrations.AddField(
            model_name='essay',
            name='translator',
            field=models.ForeignKey(blank=True, limit_choices_to={'job': 'translator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays_translator', to='app.producer'),
        ),
    ]
